language: node_js
node_js:
  - "0.10"

before_install:
  - "export BROWSERS=Firefox"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - npm run cover-publish
addons:
  code_climate:
    repo_token:
      # # get your token from https://codeclimate.com/github/benjamine/jsondiffpatch
      # gem install travis
      # travis encrypt <projecttoken>
      secure: "project's encrypted token"
